### ISSUE TITLE
Make your buttons pretty! 

### ISSUE THREAD

**Issue by tylerwince** [roamhacker/SmartBlocks#106]
## 📋 Describe the new feature/idea/enhancement you are requesting
This css snippet will make your buttons really pretty. Nice when used in conjunction with {{}} for executing Smartblocks as described here: https://roamresearch.com/#/app/roamhacker/page/qFqLurfD6

This came from the [Zenith codebase](https://github.com/azlen/roam-themes/blob/master/zenith.css).

```css
/* BUTTON */
.block-bullet-view .bp3-button:not([class*="bp3-icon"]) {
    background: transparent !important;
    color: rgb(30,144,255) !important;
    padding: 4px 14px;
    line-height: 2em;
    font-weight: 600;
    border-radius: 2em !important;
    border: 1px solid rgba(30,144,255, 0.5) !important;
    box-shadow: none !important;
}
```
